version: "3.5"

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
